### PR TITLE
pixel utilities (originally garbage utilities)

### PR DESCRIPTION
**Pull request by LittleBlueGamer427**
just some garbage blocks.
(note: im not sure why the things being unlisted)
image

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
1) Its unlisted in your fork cuz the gallery is hardcoded to work only with my repository :trollface: 

2) Id prefer if you didnt use the name Garbage utilities

**Comment by LittleBlueGamer427** [comment]
> 1. Its unlisted in your fork cuz the gallery is hardcoded to work only with my repository :trollface:
> 2. Id prefer if you didnt use the name Garbage utilities

ill rename it to pixel utilities as i announced in my gamejolt community

**Comment by LittleBlueGamer427** [comment]
applied the change to my gallery now doing it to the fork

**Comment by LittleBlueGamer427** [comment]
> 1. Its unlisted in your fork cuz the gallery is hardcoded to work only with my repository :trollface:
> 2. Id prefer if you didnt use the name Garbage utilities

finished the change, the class and register parts of the code still say garbageutilities but the id and name are changed

**Comment by SharkPool-SP** [comment]
I'll merge later today, there's a lot of formatting things I need to fix

**Pull request merged**
