### PR TITLE
Do these cool things

### PR DESCRIPTION
**Pull request by IonMakesGarbage**
there is no json idk how to do that

### CODE REVIEW

**Comment by SurvExe1Pc** [comment]
lol yeah
________________________________
From: IonMakesGarbage ***@***.***>
Sent: Thursday, October 12, 2023 3:13 PM
To: SharkPool-SP/SharkPools-Extensions ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SharkPool-SP/SharkPools-Extensions] Do these cool things (PR #19)


there is no json idk how to do that

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/SharkPool-SP/SharkPools-Extensions/pull/19

Commit Summary

  *   81c9cc2<https://github.com/SharkPool-SP/SharkPools-Extensions/pull/19/commits/81c9cc22cc647cd89aa4319e53c0f9ba372d340e> Add files via upload
  *   c339e44<https://github.com/SharkPool-SP/SharkPools-Extensions/pull/19/commits/c339e449845d00e43284d65073215a868235fc68> Add files via upload

File Changes

(2 files<https://github.com/SharkPool-SP/SharkPools-Extensions/pull/19/files>)

  *   A extension-code/2000 Expanded.js<https://github.com/SharkPool-SP/SharkPools-Extensions/pull/19/files#diff-42918a9b07d133043793cf5f7d098026ae7e5221204d725009fc5d25cd17d274> (139)
  *   A extension-thumbs/2000_Expanded.svg<https://github.com/SharkPool-SP/SharkPools-Extensions/pull/19/files#diff-4561f74b8d12a2970eb9fc9d4fdad27928822286702d85559faef51e26cc2d59> (1)

Patch Links:

  *   https://github.com/SharkPool-SP/SharkPools-Extensions/pull/19.patch
  *   https://github.com/SharkPool-SP/SharkPools-Extensions/pull/19.diff

**Comment by IonMakesGarbage** [comment]
its so cool

**Comment by SharkPool-SP** [comment]
I should simplify this to a single block but eh, not a huge deal

**Comment by SurvExe1Pc** [comment]
check what i sent you on my github in ur pr
________________________________

**Pull request merged**
