### PR TITLE
pull request for add a extension

### PR DESCRIPTION
**Pull request by Alejin2014**
Pls Sharkpool or someone. I want to add my extension Almejas Utils. I'm Alejo.14 from the Discord server.

### CODE REVIEW

**Comment by Alejin2014** [comment]
what

**Comment by Alejin2014** [comment]
noo

**Comment by SharkPool-SP** [comment]
> noo
> 
> 

Just edit the file and update the code

**Comment by SharkPool-SP** [comment]
> noo
> 
> 

Oh nvm, GitHub mobile is being buggy

**Comment by Alejin2014** [comment]
So is it okay now?

**Comment by LittleBlueGamer427** [comment]
let me test this hold on

**Comment by LittleBlueGamer427** [comment]
contrast is too low, make the blocks darker

**Comment by LittleBlueGamer427** [comment]
like fr this is a little hard to read but i can still read it but contrast is kinda important
image

**Comment by LittleBlueGamer427** [comment]
image
something like this would be good enough

**Comment by Alejin2014** [comment]
Ok

**Comment by Alejin2014** [comment]
Done

**Comment by SharkPool-SP** [comment]
> Done

The extension was made using Turbobuilder, I cant merge this due to its shitty format

**Comment by LittleBlueGamer427** [comment]
i can accept those btw
(not competing)

**Pull request closed without merging**
