### PR TITLE
Use New Bounds System -- Lazy-Collisions

### PR DESCRIPTION
**Pull request by fo-od**
makes it use getBounds which is better

### CODE REVIEW

**Comment by fo-od** [comment]
bugs fixed, blocks tested, but i think having rounding as an option would be better

**Comment by fo-od** [comment]
i cant think of a good way to implement the optional rounding though, so comment if you can think of a good way to implement it

**Comment by SharkPool-SP** [comment]
We don't need translate for camera. It's penguinmod only, not in Turbowarp.

**Comment by fo-od** [comment]
> We don't need translate for camera. It's penguinmod only, not in Turbowarp.

i just did that so i could modify the function for the needs of the ext, unless theres a better way to do that. and i have it translate for camera because its incorrect if there is zoom

**Comment by SharkPool-SP** [comment]
> > We don't need translate for camera. It's penguinmod only, not in Turbowarp.
> 
> i just did that so i could modify the function for the needs of the ext, unless theres a better way to do that. and i have it translate for camera because it was incorrect if there was zoom

Strange, maybe theres a different getAABB function. Also why did you remove the offset arguments

**Comment by fo-od** [comment]
> Strange, maybe theres a different getAABB function. Also why did you remove the offset arguments

if you are talking about `offset = offset + Math.round(spriteAtt[2] + spriteAtt2[2]);` it isnt needed

**Comment by SharkPool-SP** [comment]
> > Strange, maybe theres a different getAABB function. Also why did you remove the offset arguments
> 
> if you are talking about `offset = offset + Math.round(spriteAtt[2] + spriteAtt2[2]);` it isnt needed

I'm talking about the offset arguments

**Comment by fo-od** [comment]
> I'm talking about the offset arguments
wdym? i didnt remove offset arguments, can you tell me which lines?

**Comment by SharkPool-SP** [comment]
> > I'm talking about the offset arguments
> 
> wdym? i dont remember removing any offset arguments, can you tell me which lines?

oh wait nvm. Github is confusing me lol

**Comment by fo-od** [comment]
well its ready to merge, unless theres some changes that you want to be made

**Comment by SharkPool-SP** [comment]
> well its ready to merge, unless theres some changes that you want to be made

Okay, as I said in the other PR I wont be able to get to merging these any time soon as Im busy with other stuff. Give it some time

**Comment by SharkPool-SP** [comment]
Ive been looking over it. You dont need translate4camera nor getBounds, the old system works fine, it just needs to be offset by the stretch, which can be found in the renderer

**Comment by fo-od** [comment]
> Ive been looking over it. You dont need translate4camera nor getBounds, the old system works fine, it just needs to be offset by the stretch, which can be found in the renderer. It also has a rotation center too in the drawable. You can look at my renderer control extension for some help

could you possibly link the source for the renderer and drawable? i don't really know what those are (this is my first time actually working with the VM) and its kind of hard to understand your ext without knowing what vm.renderer has

**Comment by SharkPool-SP** [comment]
> > Ive been looking over it. You dont need translate4camera nor getBounds, the old system works fine, it just needs to be offset by the stretch, which can be found in the renderer. It also has a rotation center too in the drawable. You can look at my renderer control extension for some help
> 
> 
> 
> could you possibly link the source for the renderer and drawable? i don't really know what those are (this is my first time actually working with the VM) and its kind of hard to understand your ext

vm.renderer is the renderer. The drawable is:

renderer._allDrawables[target.drawableId]

**Comment by fo-od** [comment]
> > > Ive been looking over it. You dont need translate4camera nor getBounds, the old system works fine, it just needs to be offset by the stretch, which can be found in the renderer. It also has a rotation center too in the drawable. You can look at my renderer control extension for some help
> > 
> > 
> > could you possibly link the source for the renderer and drawable? i don't really know what those are (this is my first time actually working with the VM) and its kind of hard to understand your ext
> 
> vm.renderer is the renderer. The drawable is:
> 
> renderer._allDrawables[target.drawableId]

btw is this intentional (it not being the same as the sprite) or do i fix that
image

**Comment by SharkPool-SP** [comment]
Just put it into the console, you'll get a list of functions and data

**Comment by fo-od** [comment]
> Just put it into the console, you'll get a list of functions and data

just console.log it?

**Comment by fo-od** [comment]
uhh i dont know what exactly to put in the console

**Comment by SharkPool-SP** [comment]
> what exactly do i put in the console?

The drawable whatever you want

**Comment by fo-od** [comment]
ok well i dont really know how to make it work with the rotation center

**Comment by SharkPool-SP** [comment]
> ok well i dont really know what to do with the rotation center

first array item is x rotation offset, second is y rotation offset

**Comment by fo-od** [comment]
> > ok well i dont really know what to do with the rotation center
> 
> first array item is x rotation offset, second is y rotation offset

yeah ik that I just don't know how to include those values

**Comment by SharkPool-SP** [comment]
> > > ok well i dont really know what to do with the rotation center
> 
> > 
> 
> > first array item is x rotation offset, second is y rotation offset
> 
> 
> 
> yeah ik that I just don't know how to include those values

You said that it won't work if the sprite was offset from the center

**Comment by fo-od** [comment]
> > > > ok well i dont really know what to do with the rotation center
> > 
> > 
> > > 
> > 
> > 
> > > first array item is x rotation offset, second is y rotation offset
> > 
> > 
> > yeah ik that I just don't know how to include those values
> 
> You said that it won't work if the sprite was offset from the center

Im not smart enough to figure out how to fix that using the rotation center though 😭

**Comment by fo-od** [comment]
Ok so actually i got it like half done
[Screen recording 2024-05-15 11.36.53 AM.webm](https://github.com/SharkPool-SP/SharkPools-Extensions/assets/99752044/594fa243-449c-4a95-8c40-2fe2d66f686e)

**Comment by fo-od** [comment]
and this is the information that i know
image

**Comment by SharkPool-SP** [comment]
> and this is the information that i know about rotation center
> 
> image
> 
> 

It would be the same corner of you subtracted it

**Comment by SharkPool-SP** [comment]
Theres still things needed for us to fix:
-use the AABB of both sprites dimensions (subtract them) for placing/checking
-handle rotation centers

**Comment by SharkPool-SP** [comment]
Im close to fixing everything. Just need to fix "isOnSprite". Ill do it tmw as its 2am rn.

**Pull request merged**
